// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCppBlgoUUW3s-IwrCrkIXaZREEe3q1ie0',
    appId: '1:641542597812:web:3258560995d98d38ca7be1',
    messagingSenderId: '641542597812',
    projectId: 'socialmediaasian',
    authDomain: 'socialmediaasian.firebaseapp.com',
    storageBucket: 'socialmediaasian.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTFXq6Zzx8Qc7ixPtwkMQCRYgfvfQIjOQ',
    appId: '1:641542597812:android:c864657b3e09f9ceca7be1',
    messagingSenderId: '641542597812',
    projectId: 'socialmediaasian',
    storageBucket: 'socialmediaasian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtGiCUh_ZsG2pSjSvOSTQOEMRBv_fWsPU',
    appId: '1:641542597812:ios:6c56d189ad0c62a2ca7be1',
    messagingSenderId: '641542597812',
    projectId: 'socialmediaasian',
    storageBucket: 'socialmediaasian.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );
}
